import { post, route } from 'remix/fetch-router/routes'

export const routes = route({
	home: '/',
	chat: '/chat',
	chatThread: '/chat/:threadId',
	chatThreads: '/chat-threads',
	chatThreadsCreate: post('/chat-threads'),
	chatThreadsUpdate: post('/chat-threads/update'),
	chatThreadsDelete: post('/chat-threads/delete'),
	ketoEntries: '/keto-entries',
	ketoEntriesCreate: post('/keto-entries'),
	ketoEntriesUpdate: post('/keto-entries/update'),
	ketoEntriesDelete: post('/keto-entries/delete'),
	ketoGoals: '/keto-goals',
	ketoGoalsUpdate: post('/keto-goals'),
	health: '/health',
	login: '/login',
	signup: '/signup',
	account: '/account',
	auth: post('/auth'),
	session: '/session',
	logout: post('/logout'),
	passwordResetRequest: post('/password-reset'),
	passwordResetConfirm: post('/password-reset/confirm'),
})
